### ISSUE TITLE
Problem with multi threading? - Unbound variable: CL-MOCK::*RECORDP*

### ISSUE THREAD

**Issue by mdbergmann** [Ferada/cl-mock#5]
Hi.

I have no real prove yet, but I have a problem where cl-mock doesn't record invocations when the invocation runs in a different thread than the test setup. I see the above error message in this case then.
Not sure, do you think this could be a problem?

**Comment by mdbergmann** [comment]
Here is a quick example:

```
(defun foo (x)
           10)

(cl-mock:with-mocks ()
           (cl-mock:answer foo 11)
           (bt:make-thread (lambda () (foo 15)))
           (sleep 0.5)
           (cl-mock:invocations 'foo))
```

Now I'm not sure, if this is as designed?

**Comment by Ferada** [comment]
Right, there's nothing at all to support threading in any way, those variables will have to be shared via bt's mechanisms to work out. I suppose it would make sense to at least document the way to do this though.

**Comment by mdbergmann** [comment]
But I'm not sure I understand.
A 'global' variable, like what `CL-MOCK::*RECORDP*` seems to be (without further looking), why would it not be accessible from different threads?
Maybe I don't understand the problem.

**Comment by Ferada** [comment]
`(defvar *recordp*)` is just defining the variable, but it's initially unbound, therefore even when `with-mocks` binds it, that binding isn't visible in the spawned thread though, unless bt is instructed to copy over that binding - that's what I think happens at the moment.

So `initial-bindings` would have to be set on `make-thread`, though that's cumbersome.

Maybe that would require a change, instead of via `let`, go `setf` and reset the value in an `unwind-protect`.

I'm not super in the CL world right now, if you have a different idea for how to go about it, please make a note here.

**Comment by mdbergmann** [comment]
No prob.
I will give it some thought.
